package com.zukron.coronadata.model;

import com.zukron.coronadata.tools.Util;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

/**
 * Project name is Corona Data App
 * Created by Zukron Alviandy R on 7/10/2020
 */
public class Country extends StatusData {
    private String iso2;
    private String name;
    private static Map<String, String> allCountryIso = new HashMap<>();
    private static Map<String, String> allCountrySlug = new HashMap<>();

    public String getIso2() {
        return iso2;
    }

    public void setIso2(String iso2) {
        this.iso2 = iso2;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public static ArrayList<String> allCountry() {
        ArrayList<String> countries = new ArrayList<>();

        countries.add("Afghanistan");
        countries.add("Albania");
        countries.add("Algeria");
        countries.add("Andorra");
        countries.add("Angola");
        countries.add("Antigua and Barbuda");
        countries.add("Argentina");
        countries.add("Armenia");
        countries.add("Australia");
        countries.add("Austria");
        countries.add("Azerbaijan");
        countries.add("Bahamas");
        countries.add("Bahrain");
        countries.add("Bangladesh");
        countries.add("Barbados");
        countries.add("Belarus");
        countries.add("Belgium");
        countries.add("Belize");
        countries.add("Benin");
        countries.add("Bhutan");
        countries.add("Bolivia");
        countries.add("Bosnia and Herzegovina");
        countries.add("Botswana");
        countries.add("Brazil");
        countries.add("Brunei");
        countries.add("Bulgaria");
        countries.add("Burkina Faso");
        countries.add("Burundi");
        countries.add("Cambodia");
        countries.add("Cameroon");
        countries.add("Canada");
        countries.add("Central African Republic");
        countries.add("Chad");
        countries.add("Chile");
        countries.add("China");
        countries.add("Colombia");
        countries.add("Comoros");
        countries.add("Costa Rica");
        countries.add("Croatia");
        countries.add("Cuba");
        countries.add("Cyprus");
        countries.add("Czechia");
        countries.add("Denmark");
        countries.add("Djibouti");
        countries.add("Dominica");
        countries.add("Dominican Republic");
        countries.add("Ecuador");
        countries.add("Egypt");
        countries.add("El Salvador");
        countries.add("Equatorial Guinea");
        countries.add("Eritrea");
        countries.add("Estonia");
        countries.add("Ethiopia");
        countries.add("Fiji");
        countries.add("Finland");
        countries.add("France");
        countries.add("Gabon");
        countries.add("Gambia");
        countries.add("Georgia");
        countries.add("Germany");
        countries.add("Ghana");
        countries.add("Greece");
        countries.add("Grenada");
        countries.add("Guatemala");
        countries.add("Guinea");
        countries.add("Guinea Bissau");
        countries.add("Guyana");
        countries.add("Haiti");
        countries.add("Honduras");
        countries.add("Hungary");
        countries.add("Iceland");
        countries.add("India");
        countries.add("Indonesia");
        countries.add("Iran");
        countries.add("Iraq");
        countries.add("Ireland");
        countries.add("Israel");
        countries.add("Italy");
        countries.add("Jamaica");
        countries.add("Japan");
        countries.add("Jordan");
        countries.add("Kazakhstan");
        countries.add("Kenya");
        countries.add("South Korea");
        countries.add("Kosovo");
        countries.add("Kuwait");
        countries.add("Kyrgyzstan");
        countries.add("Laos");
        countries.add("Latvia");
        countries.add("Lebanon");
        countries.add("Lesotho");
        countries.add("Liberia");
        countries.add("Libya");
        countries.add("Liechtenstein");
        countries.add("Lithuania");
        countries.add("Luxembourg");
        countries.add("Madagascar");
        countries.add("Malawi");
        countries.add("Malaysia");
        countries.add("Maldives");
        countries.add("Mali");
        countries.add("Malta");
        countries.add("Mauritania");
        countries.add("Mauritius");
        countries.add("Mexico");
        countries.add("Moldova");
        countries.add("Monaco");
        countries.add("Mongolia");
        countries.add("Montenegro");
        countries.add("Morocco");
        countries.add("Mozambique");
        countries.add("Namibia");
        countries.add("Nepal");
        countries.add("Netherlands");
        countries.add("New Zealand");
        countries.add("Nicaragua");
        countries.add("Niger");
        countries.add("Nigeria");
        countries.add("Norway");
        countries.add("Oman");
        countries.add("Pakistan");
        countries.add("Panama");
        countries.add("Papua New Guinea");
        countries.add("Paraguay");
        countries.add("Peru");
        countries.add("Philippines");
        countries.add("Poland");
        countries.add("Portugal");
        countries.add("Qatar");
        countries.add("Romania");
        countries.add("Russia");
        countries.add("Rwanda");
        countries.add("Saint Kitts and Nevis");
        countries.add("Saint Lucia");
        countries.add("Saint Vincent and the Grenadines");
        countries.add("San Marino");
        countries.add("Sao Tome and Principe");
        countries.add("Saudi Arabia");
        countries.add("Senegal");
        countries.add("Serbia");
        countries.add("Seychelles");
        countries.add("Sierra Leone");
        countries.add("Singapore");
        countries.add("Slovakia");
        countries.add("Slovenia");
        countries.add("Somalia");
        countries.add("South Africa");
        countries.add("South Sudan");
        countries.add("Spain");
        countries.add("Sri Lanka");
        countries.add("Sudan");
        countries.add("Suriname");
        countries.add("Sweden");
        countries.add("Switzerland");
        countries.add("Syria");
        countries.add("Taiwan");
        countries.add("Tajikistan");
        countries.add("Tanzania");
        countries.add("Thailand");
        countries.add("Togo");
        countries.add("Trinidad and Tobago");
        countries.add("Tunisia");
        countries.add("Turkey");
        countries.add("US");
        countries.add("Uganda");
        countries.add("Ukraine");
        countries.add("United Arab Emirates");
        countries.add("United Kingdom");
        countries.add("Uruguay");
        countries.add("Uzbekistan");
        countries.add("Venezuela");
        countries.add("Vietnam");
        countries.add("Western Sahara");
        countries.add("Yemen");
        countries.add("Zambia");
        countries.add("Zimbabwe");

        return countries;
    }

    private static void setAllCountryIso() {
        allCountryIso.put("Afghanistan", "AF");
        allCountryIso.put("Albania", "AL");
        allCountryIso.put("Algeria", "DZ");
        allCountryIso.put("Andorra", "AD");
        allCountryIso.put("Angola", "AO");
        allCountryIso.put("Antigua_and_Barbuda", "AG");
        allCountryIso.put("Argentina", "AR");
        allCountryIso.put("Armenia", "AM");
        allCountryIso.put("Australia", "AU");
        allCountryIso.put("Austria", "AT");
        allCountryIso.put("Azerbaijan", "AZ");
        allCountryIso.put("Bahamas", "BS");
        allCountryIso.put("Bahrain", "BH");
        allCountryIso.put("Bangladesh", "BD");
        allCountryIso.put("Barbados", "BB");
        allCountryIso.put("Belarus", "BY");
        allCountryIso.put("Belgium", "BE");
        allCountryIso.put("Belize", "BZ");
        allCountryIso.put("Benin", "BJ");
        allCountryIso.put("Bhutan", "BT");
        allCountryIso.put("Bolivia", "BO");
        allCountryIso.put("Bosnia_and_Herzegovina", "BA");
        allCountryIso.put("Botswana", "BW");
        allCountryIso.put("Brazil", "BR");
        allCountryIso.put("Brunei", "BN");
        allCountryIso.put("Bulgaria", "BG");
        allCountryIso.put("Burkina_Faso", "BF");
        allCountryIso.put("Burundi", "BI");
        allCountryIso.put("Cambodia", "KH");
        allCountryIso.put("Cameroon", "CM");
        allCountryIso.put("Canada", "CA");
        allCountryIso.put("Central_African_Republic", "CF");
        allCountryIso.put("Chad", "TD");
        allCountryIso.put("Chile", "CL");
        allCountryIso.put("China", "CN");
        allCountryIso.put("Colombia", "CO");
        allCountryIso.put("Comoros", "KM");
        allCountryIso.put("Costa_Rica", "CR");
        allCountryIso.put("Croatia", "HR");
        allCountryIso.put("Cuba", "CU");
        allCountryIso.put("Cyprus", "CY");
        allCountryIso.put("Czechia", "CZ");
        allCountryIso.put("Denmark", "DK");
        allCountryIso.put("Djibouti", "DJ");
        allCountryIso.put("Dominica", "DM");
        allCountryIso.put("Dominican_Republic", "DO");
        allCountryIso.put("Ecuador", "EC");
        allCountryIso.put("Egypt", "EG");
        allCountryIso.put("El_Salvador", "SV");
        allCountryIso.put("Equatorial_Guinea", "GQ");
        allCountryIso.put("Eritrea", "ER");
        allCountryIso.put("Estonia", "EE");
        allCountryIso.put("Ethiopia", "ET");
        allCountryIso.put("Fiji", "FJ");
        allCountryIso.put("Finland", "FI");
        allCountryIso.put("France", "FR");
        allCountryIso.put("Gabon", "GA");
        allCountryIso.put("Gambia", "GM");
        allCountryIso.put("Georgia", "GE");
        allCountryIso.put("Germany", "DE");
        allCountryIso.put("Ghana", "GH");
        allCountryIso.put("Greece", "GR");
        allCountryIso.put("Grenada", "GD");
        allCountryIso.put("Guatemala", "GT");
        allCountryIso.put("Guinea", "GN");
        allCountryIso.put("Guinea_Bissau", "GW");
        allCountryIso.put("Guyana", "GY");
        allCountryIso.put("Haiti", "HT");
        allCountryIso.put("Honduras", "HN");
        allCountryIso.put("Hungary", "HU");
        allCountryIso.put("Iceland", "IS");
        allCountryIso.put("India", "IN");
        allCountryIso.put("Indonesia", "ID");
        allCountryIso.put("Iran", "IR");
        allCountryIso.put("Iraq", "IQ");
        allCountryIso.put("Ireland", "IE");
        allCountryIso.put("Israel", "IL");
        allCountryIso.put("Italy", "IT");
        allCountryIso.put("Jamaica", "JM");
        allCountryIso.put("Japan", "JP");
        allCountryIso.put("Jordan", "JO");
        allCountryIso.put("Kazakhstan", "KZ");
        allCountryIso.put("Kenya", "KE");
        allCountryIso.put("South_Korea", "KR");
        allCountryIso.put("Kosovo", "XK");
        allCountryIso.put("Kuwait", "KW");
        allCountryIso.put("Kyrgyzstan", "KG");
        allCountryIso.put("Laos", "LA");
        allCountryIso.put("Latvia", "LV");
        allCountryIso.put("Lebanon", "LB");
        allCountryIso.put("Lesotho", "LS");
        allCountryIso.put("Liberia", "LR");
        allCountryIso.put("Libya", "LY");
        allCountryIso.put("Liechtenstein", "LI");
        allCountryIso.put("Lithuania", "LT");
        allCountryIso.put("Luxembourg", "LU");
        allCountryIso.put("Madagascar", "MG");
        allCountryIso.put("Malawi", "MW");
        allCountryIso.put("Malaysia", "MY");
        allCountryIso.put("Maldives", "MV");
        allCountryIso.put("Mali", "ML");
        allCountryIso.put("Malta", "MT");
        allCountryIso.put("Mauritania", "MR");
        allCountryIso.put("Mauritius", "MU");
        allCountryIso.put("Mexico", "MX");
        allCountryIso.put("Moldova", "MD");
        allCountryIso.put("Monaco", "MC");
        allCountryIso.put("Mongolia", "MN");
        allCountryIso.put("Montenegro", "ME");
        allCountryIso.put("Morocco", "MA");
        allCountryIso.put("Mozambique", "MZ");
        allCountryIso.put("Namibia", "NA");
        allCountryIso.put("Nepal", "NP");
        allCountryIso.put("Netherlands", "NL");
        allCountryIso.put("New_Zealand", "NZ");
        allCountryIso.put("Nicaragua", "NI");
        allCountryIso.put("Niger", "NE");
        allCountryIso.put("Nigeria", "NG");
        allCountryIso.put("Norway", "NO");
        allCountryIso.put("Oman", "OM");
        allCountryIso.put("Pakistan", "PK");
        allCountryIso.put("Panama", "PA");
        allCountryIso.put("Papua_New_Guinea", "PG");
        allCountryIso.put("Paraguay", "PY");
        allCountryIso.put("Peru", "PE");
        allCountryIso.put("Philippines", "PH");
        allCountryIso.put("Poland", "PL");
        allCountryIso.put("Portugal", "PT");
        allCountryIso.put("Qatar", "QA");
        allCountryIso.put("Romania", "RO");
        allCountryIso.put("Russia", "RU");
        allCountryIso.put("Rwanda", "RW");
        allCountryIso.put("Saint_Kitts_and_Nevis", "KN");
        allCountryIso.put("Saint_Lucia", "LC");
        allCountryIso.put("Saint_Vincent_and_the_Grenadines", "VC");
        allCountryIso.put("San_Marino", "SM");
        allCountryIso.put("Sao_Tome_and_Principe", "ST");
        allCountryIso.put("Saudi_Arabia", "SA");
        allCountryIso.put("Senegal", "SN");
        allCountryIso.put("Serbia", "RS");
        allCountryIso.put("Seychelles", "SC");
        allCountryIso.put("Sierra_Leone", "SL");
        allCountryIso.put("Singapore", "SG");
        allCountryIso.put("Slovakia", "SK");
        allCountryIso.put("Slovenia", "SI");
        allCountryIso.put("Somalia", "SO");
        allCountryIso.put("South_Africa", "ZA");
        allCountryIso.put("South_Sudan", "SS");
        allCountryIso.put("Spain", "ES");
        allCountryIso.put("Sri_Lanka", "LK");
        allCountryIso.put("Sudan", "SD");
        allCountryIso.put("Suriname", "SR");
        allCountryIso.put("Sweden", "SE");
        allCountryIso.put("Switzerland", "CH");
        allCountryIso.put("Syria", "SY");
        allCountryIso.put("Taiwan", "TW");
        allCountryIso.put("Tajikistan", "TJ");
        allCountryIso.put("Tanzania", "TZ");
        allCountryIso.put("Thailand", "TH");
        allCountryIso.put("Togo", "TG");
        allCountryIso.put("Trinidad_and_Tobago", "TT");
        allCountryIso.put("Tunisia", "TN");
        allCountryIso.put("Turkey", "TR");
        allCountryIso.put("US", "US");
        allCountryIso.put("Uganda", "UG");
        allCountryIso.put("Ukraine", "UA");
        allCountryIso.put("United_Arab_Emirates", "AE");
        allCountryIso.put("United_Kingdom", "GB");
        allCountryIso.put("Uruguay", "UY");
        allCountryIso.put("Uzbekistan", "UZ");
        allCountryIso.put("Venezuela", "VE");
        allCountryIso.put("Vietnam", "VN");
        allCountryIso.put("Western_Sahara", "EH");
        allCountryIso.put("Yemen", "YE");
        allCountryIso.put("Zambia", "ZM");
        allCountryIso.put("Zimbabwe", "ZW");
    }

    private static void setAllCountrySlug() {
        allCountrySlug.put("Cape_Verde", "cape-verde");
        allCountrySlug.put("Guyana", "guyana");
        allCountrySlug.put("Lebanon", "lebanon");
        allCountrySlug.put("Tunisia", "tunisia");
        allCountrySlug.put("US", "united-states");
        allCountrySlug.put("Mongolia", "mongolia");
        allCountrySlug.put("Sudan", "sudan");
        allCountrySlug.put("Tokelau", "tokelau");
        allCountrySlug.put("Albania", "albania");
        allCountrySlug.put("Bhutan", "bhutan");
        allCountrySlug.put("Gibraltar", "gibraltar");
        allCountrySlug.put("Iceland", "iceland");
        allCountrySlug.put("US_Minor_Outlying_Islands", "us-minor-outlying-islands");
        allCountrySlug.put("Viet_Nam", "vietnam");
        allCountrySlug.put("Canada", "canada");
        allCountrySlug.put("Kiribati", "kiribati");
        allCountrySlug.put("Netherlands_Antilles", "netherlands-antilles");
        allCountrySlug.put("Sweden", "sweden");
        allCountrySlug.put("Saint-Barthélemy", "saint-barthélemy");
        allCountrySlug.put("Bouvet_Island", "bouvet-island");
        allCountrySlug.put("Estonia", "estonia");
        allCountrySlug.put("Grenada", "grenada");
        allCountrySlug.put("Niger", "niger");
        allCountrySlug.put("Guernsey", "guernsey");
        allCountrySlug.put("Indonesia", "indonesia");
        allCountrySlug.put("Turkmenistan", "turkmenistan");
        allCountrySlug.put("Western_Sahara", "western-sahara");
        allCountrySlug.put("Croatia", "croatia");
        allCountrySlug.put("Japan", "japan");
        allCountrySlug.put("Libya", "libya");
        allCountrySlug.put("Turkey", "turkey");
        allCountrySlug.put("Bermuda", "bermuda");
        allCountrySlug.put("Latvia", "latvia");
        allCountrySlug.put("Timor-Leste", "timor-leste");
        allCountrySlug.put("Italy", "italy");
        allCountrySlug.put("San_Marino", "san-marino");
        allCountrySlug.put("Virgin_Islands_US", "virgin-islands");
        allCountrySlug.put("British_Indian_Ocean_Territory", "british-indian-ocean-territory");
        allCountrySlug.put("Gambia", "gambia");
        allCountrySlug.put("Namibia", "namibia");
        allCountrySlug.put("Zambia", "zambia");
        allCountrySlug.put("Swaziland", "swaziland");
        allCountrySlug.put("American_Samoa", "american-samoa");
        allCountrySlug.put("Congo_(Kinshasa)", "congo-kinshasa");
        allCountrySlug.put("Djibouti", "djibouti");
        allCountrySlug.put("Nicaragua", "nicaragua");
        allCountrySlug.put("Senegal", "senegal");
        allCountrySlug.put("Turks_and_Caicos_Islands", "turks-and-caicos-islands");
        allCountrySlug.put("United_Arab_Emirates", "united-arab-emirates");
        allCountrySlug.put("Lesotho", "lesotho");
        allCountrySlug.put("Lithuania", "lithuania");
        allCountrySlug.put("Mauritania", "mauritania");
        allCountrySlug.put("Fiji", "fiji");
        allCountrySlug.put("Belgium", "belgium");
        allCountrySlug.put("France", "france");
        allCountrySlug.put("Heard_and_Mcdonald_Islands", "heard-and-mcdonald-islands");
        allCountrySlug.put("Palestinian_Territory", "palestine");
        allCountrySlug.put("Bosnia_and_Herzegovina", "bosnia-and-herzegovina");
        allCountrySlug.put("Chad", "chad");
        allCountrySlug.put("Kyrgyzstan", "kyrgyzstan");
        allCountrySlug.put("Rwanda", "rwanda");
        allCountrySlug.put("Svalbard_and_Jan_Mayen_Islands", "svalbard-and-jan-mayen-islands");
        allCountrySlug.put("Uruguay", "uruguay");
        allCountrySlug.put("Guinea", "guinea");
        allCountrySlug.put("Philippines", "philippines");
        allCountrySlug.put("Burkina_Faso", "burkina-faso");
        allCountrySlug.put("Germany", "germany");
        allCountrySlug.put("Lao_PDR", "lao-pdr");
        allCountrySlug.put("Montenegro", "montenegro");
        allCountrySlug.put("Guadeloupe", "guadeloupe");
        allCountrySlug.put("Nauru", "nauru");
        allCountrySlug.put("Pitcairn", "pitcairn");
        allCountrySlug.put("Paraguay", "paraguay");
        allCountrySlug.put("Antigua_and_Barbuda", "antigua-and-barbuda");
        allCountrySlug.put("Côte_d'Ivoire", "cote-divoire");
        allCountrySlug.put("Egypt", "egypt");
        allCountrySlug.put("Afghanistan", "afghanistan");
        allCountrySlug.put("Mali", "mali");
        allCountrySlug.put("Puerto_Rico", "puerto-rico");
        allCountrySlug.put("Trinidad_and_Tobago", "trinidad-and-tobago");
        allCountrySlug.put("Cameroon", "cameroon");
        allCountrySlug.put("Micronesia_Federated_States_of", "micronesia");
        allCountrySlug.put("Suriname", "suriname");
        allCountrySlug.put("Malawi", "malawi");
        allCountrySlug.put("Azerbaijan", "azerbaijan");
        allCountrySlug.put("Belarus", "belarus");
        allCountrySlug.put("El_Salvador", "el-salvador");
        allCountrySlug.put("Malaysia", "malaysia");
        allCountrySlug.put("Monaco", "monaco");
        allCountrySlug.put("Norfolk_Island", "norfolk-island");
        allCountrySlug.put("Peru", "peru");
        allCountrySlug.put("Jordan", "jordan");
        allCountrySlug.put("Netherlands", "netherlands");
        allCountrySlug.put("Palau", "palau");
        allCountrySlug.put("Sao_Tome_and_Principe", "sao-tome-and-principe");
        allCountrySlug.put("Greenland", "greenland");
        allCountrySlug.put("Israel", "israel");
        allCountrySlug.put("Venezuela", "venezuela");
        allCountrySlug.put("Martinique", "martinique");
        allCountrySlug.put("Saint_Lucia", "saint-lucia");
        allCountrySlug.put("Taiwan_Republic_of_China", "taiwan");
        allCountrySlug.put("Austria", "austria");
        allCountrySlug.put("Georgia", "georgia");
        allCountrySlug.put("India", "india");
        allCountrySlug.put("Kazakhstan", "kazakhstan");
        allCountrySlug.put("Burundi", "burundi");
        allCountrySlug.put("Guinea_Bissau", "guinea-bissau");
        allCountrySlug.put("New_Zealand", "new-zealand");
        allCountrySlug.put("Togo", "togo");
        allCountrySlug.put("Saudi_Arabia", "saudi-arabia");
        allCountrySlug.put("Comoros", "comoros");
        allCountrySlug.put("Cyprus", "cyprus");
        allCountrySlug.put("Panama", "panama");
        allCountrySlug.put("Haiti", "haiti");
        allCountrySlug.put("Saint_Pierre_and_Miquelon", "saint-pierre-and-miquelon");
        allCountrySlug.put("Slovakia", "slovakia");
        allCountrySlug.put("Uganda", "uganda");
        allCountrySlug.put("Argentina", "argentina");
        allCountrySlug.put("China", "china");
        allCountrySlug.put("Faroe_Islands", "faroe-islands");
        allCountrySlug.put("Guam", "guam");
        allCountrySlug.put("French_Southern_Territories", "french-southern-territories");
        allCountrySlug.put("Honduras", "honduras");
        allCountrySlug.put("Isle_of_Man", "isle-of-man");
        allCountrySlug.put("Mayotte", "mayotte");
        allCountrySlug.put("Botswana", "botswana");
        allCountrySlug.put("Central_African_Republic", "central-african-republic");
        allCountrySlug.put("Wallis_and_Futuna_Islands", "wallis-and-futuna-islands");
        allCountrySlug.put("Russian_Federation", "russia");
        allCountrySlug.put("Syrian_Arab_Republic_(Syria)", "syria");
        allCountrySlug.put("Australia", "australia");
        allCountrySlug.put("Falkland_Islands_(Malvinas)", "falkland-islands-malvinas");
        allCountrySlug.put("Iraq", "iraq");
        allCountrySlug.put("Korea_(South)", "korea-south");
        allCountrySlug.put("Malta", "malta");
        allCountrySlug.put("Oman", "oman");
        allCountrySlug.put("Republic_of_Kosovo", "kosovo");
        allCountrySlug.put("Bahamas", "bahamas");
        allCountrySlug.put("Yemen", "yemen");
        allCountrySlug.put("Algeria", "algeria");
        allCountrySlug.put("Romania", "romania");
        allCountrySlug.put("Bahrain", "bahrain");
        allCountrySlug.put("Costa_Rica", "costa-rica");
        allCountrySlug.put("Switzerland", "switzerland");
        allCountrySlug.put("Benin", "benin");
        allCountrySlug.put("Tajikistan", "tajikistan");
        allCountrySlug.put("Andorra", "andorra");
        allCountrySlug.put("Uzbekistan", "uzbekistan");
        allCountrySlug.put("Antarctica", "antarctica");
        allCountrySlug.put("British_Virgin_Islands", "british-virgin-islands");
        allCountrySlug.put("Holy_See_(Vatican_City_State)", "holy-see-vatican-city-state");
        allCountrySlug.put("Ukraine", "ukraine");
        allCountrySlug.put("French_Guiana", "french-guiana");
        allCountrySlug.put("Hungary", "hungary");
        allCountrySlug.put("South_Africa", "south-africa");
        allCountrySlug.put("Spain", "spain");
        allCountrySlug.put("Mexico", "mexico");
        allCountrySlug.put("Morocco", "morocco");
        allCountrySlug.put("Sri_Lanka", "sri-lanka");
        allCountrySlug.put("Thailand", "thailand");
        allCountrySlug.put("Guatemala", "guatemala");
        allCountrySlug.put("Liechtenstein", "liechtenstein");
        allCountrySlug.put("Marshall_Islands", "marshall-islands");
        allCountrySlug.put("Nepal", "nepal");
        allCountrySlug.put("Armenia", "armenia");
        allCountrySlug.put("Maldives", "maldives");
        allCountrySlug.put("Colombia", "colombia");
        allCountrySlug.put("Hong_Kong_SAR_China", "hong-kong-sar-china");
        allCountrySlug.put("Myanmar", "myanmar");
        allCountrySlug.put("Zimbabwe", "zimbabwe");
        allCountrySlug.put("Vanuatu", "vanuatu");
        allCountrySlug.put("Moldova", "moldova");
        allCountrySlug.put("Papua_New_Guinea", "papua-new-guinea");
        allCountrySlug.put("Serbia", "serbia");
        allCountrySlug.put("Korea_(North)", "korea-north");
        allCountrySlug.put("Saint_Vincent_and_Grenadines", "saint-vincent-and-the-grenadines");
        allCountrySlug.put("Brunei_Darussalam", "brunei");
        allCountrySlug.put("Cocos_(Keeling)_Islands", "cocos-keeling-islands");
        allCountrySlug.put("Madagascar", "madagascar");
        allCountrySlug.put("South_Sudan", "south-sudan");
        allCountrySlug.put("Aruba", "aruba");
        allCountrySlug.put("Greece", "greece");
        allCountrySlug.put("Congo_(Brazzaville)", "congo-brazzaville");
        allCountrySlug.put("Poland", "poland");
        allCountrySlug.put("Kuwait", "kuwait");
        allCountrySlug.put("Liberia", "liberia");
        allCountrySlug.put("Bolivia", "bolivia");
        allCountrySlug.put("Dominica", "dominica");
        allCountrySlug.put("Ethiopia", "ethiopia");
        allCountrySlug.put("Qatar", "qatar");
        allCountrySlug.put("Gabon", "gabon");
        allCountrySlug.put("Macedonia_Republic_of", "macedonia");
        allCountrySlug.put("New_Caledonia", "new-caledonia");
        allCountrySlug.put("ALA_Aland_Islands", "ala-aland-islands");
        allCountrySlug.put("Barbados", "barbados");
        allCountrySlug.put("Luxembourg", "luxembourg");
        allCountrySlug.put("Saint_Helena", "saint-helena");
        allCountrySlug.put("Seychelles", "seychelles");
        allCountrySlug.put("Angola", "angola");
        allCountrySlug.put("Chile", "chile");
        allCountrySlug.put("Portugal", "portugal");
        allCountrySlug.put("Samoa", "samoa");
        allCountrySlug.put("Cayman_Islands", "cayman-islands");
        allCountrySlug.put("Finland", "finland");
        allCountrySlug.put("Tuvalu", "tuvalu");
        allCountrySlug.put("French_Polynesia", "french-polynesia");
        allCountrySlug.put("Ghana", "ghana");
        allCountrySlug.put("Saint-Martin_(French_part)", "saint-martin-french-part");
        allCountrySlug.put("United_Kingdom", "united-kingdom");
        allCountrySlug.put("Belize", "belize");
        allCountrySlug.put("Bulgaria", "bulgaria");
        allCountrySlug.put("Equatorial_Guinea", "equatorial-guinea");
        allCountrySlug.put("Réunion", "réunion");
        allCountrySlug.put("Christmas_Island", "christmas-island");
        allCountrySlug.put("Eritrea", "eritrea");
        allCountrySlug.put("Tonga", "tonga");
        allCountrySlug.put("Czech_Republic", "czech-republic");
        allCountrySlug.put("Dominican_Republic", "dominican-republic");
        allCountrySlug.put("Nigeria", "nigeria");
        allCountrySlug.put("Saint_Kitts_and_Nevis", "saint-kitts-and-nevis");
        allCountrySlug.put("Sierra_Leone", "sierra-leone");
        allCountrySlug.put("Cambodia", "cambodia");
        allCountrySlug.put("Ecuador", "ecuador");
        allCountrySlug.put("Pakistan", "pakistan");
        allCountrySlug.put("Bangladesh", "bangladesh");
        allCountrySlug.put("Niue", "niue");
        allCountrySlug.put("Singapore", "singapore");
        allCountrySlug.put("Slovenia", "slovenia");
        allCountrySlug.put("Cuba", "cuba");
        allCountrySlug.put("Jamaica", "jamaica");
        allCountrySlug.put("Northern_Mariana_Islands", "northern-mariana-islands");
        allCountrySlug.put("Montserrat", "montserrat");
        allCountrySlug.put("Cook_Islands", "cook-islands");
        allCountrySlug.put("Jersey", "jersey");
        allCountrySlug.put("Solomon_Islands", "solomon-islands");
        allCountrySlug.put("Tanzania_United_Republic_of", "tanzania");
        allCountrySlug.put("Anguilla", "anguilla");
        allCountrySlug.put("Brazil", "brazil");
        allCountrySlug.put("Ireland", "ireland");
        allCountrySlug.put("Somalia", "somalia");
        allCountrySlug.put("Denmark", "denmark");
        allCountrySlug.put("Macao_SAR_China", "macao-sar-china");
        allCountrySlug.put("Mauritius", "mauritius");
        allCountrySlug.put("Mozambique", "mozambique");
        allCountrySlug.put("Norway", "norway");
        allCountrySlug.put("Iran_Islamic_Republic_of", "iran");
        allCountrySlug.put("Kenya", "kenya");
    }

    public static String getCountryIso(String country) {
        if (allCountryIso.isEmpty())
            setAllCountryIso();

        return allCountryIso.get(Util.replace(country));
    }

    public static String getCountrySlug(String country) {
        if (allCountrySlug.isEmpty())
            setAllCountrySlug();

        return allCountrySlug.get(Util.replace(country));
    }
}
